export const TODO_FORM_TITLE_CHANGE = "TODO FORM TITLE CHANGE";
export const TODO_FORM_DESCRIPTION_CHANGE = "TODO FORM DESCRIPTION CHANGE";
export const TODO_FORM_SUBMIT_CHANGE = "TODO FORM SUBMIT CHANGE";
export const RESET_FORM_ON_SUBMIT = "RESET FORM ON SUBMIT";